apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base # Point to the base directory

namespace: dev

labels:
  - pairs:
      app: backend
      environment: dev

nameSuffix: -dev

