apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Daniel-Makhoba-Emmanuel/GitOps-Repo.git
    path: platform-gitops/apps/nginx/chart
    targetRevision: 'main'
    helm:
      valueFiles:
        - ../../apps/nginx/values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
