apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Daniel-Makhoba-Emmanuel/GitOps-Repo.git
    path: charts/nginx
    targetRevision: 'main'
    helm:
      valueFiles:
        - envs/stage/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
