apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stateless-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/Daniel-Makhoba-Emmanuel/GitOps-Repo.git
        revision: 'main'
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Daniel-Makhoba-Emmanuel/GitOps-Repo.git
        targetRevision: 'main'
        path: '{{path}}/chart'
        helm:
          valueFiles:
            - '{{path}}/values/dev.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
